package MyTypes::SvcAcceptedNameList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %acceptedNames_of :ATTR(:get<acceptedNames>);

__PACKAGE__->_factory(
    [ qw(        tsn
        acceptedNames

    ) ],
    {
        'tsn' => \%tsn_of,
        'acceptedNames' => \%acceptedNames_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'acceptedNames' => 'MyTypes::SvcAcceptedName',
    },
    {

        'tsn' => 'tsn',
        'acceptedNames' => 'acceptedNames',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcAcceptedNameList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcAcceptedNameList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * acceptedNames




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcAcceptedNameList
   acceptedNames =>  { # MyTypes::SvcAcceptedName
     acceptedName =>  $some_value, # string
     acceptedTsn =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

