package MyTypes::SvcCoreMetadata;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcTaxonomicBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %credRating_of :ATTR(:get<credRating>);
my %rankId_of :ATTR(:get<rankId>);
my %taxonCoverage_of :ATTR(:get<taxonCoverage>);
my %taxonCurrency_of :ATTR(:get<taxonCurrency>);
my %taxonUsageRating_of :ATTR(:get<taxonUsageRating>);
my %unacceptReason_of :ATTR(:get<unacceptReason>);

__PACKAGE__->_factory(
    [ qw(        tsn
        credRating
        rankId
        taxonCoverage
        taxonCurrency
        taxonUsageRating
        unacceptReason

    ) ],
    {
        'tsn' => \%tsn_of,
        'credRating' => \%credRating_of,
        'rankId' => \%rankId_of,
        'taxonCoverage' => \%taxonCoverage_of,
        'taxonCurrency' => \%taxonCurrency_of,
        'taxonUsageRating' => \%taxonUsageRating_of,
        'unacceptReason' => \%unacceptReason_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'credRating' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'rankId' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'taxonCoverage' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'taxonCurrency' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'taxonUsageRating' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'unacceptReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'tsn' => 'tsn',
        'credRating' => 'credRating',
        'rankId' => 'rankId',
        'taxonCoverage' => 'taxonCoverage',
        'taxonCurrency' => 'taxonCurrency',
        'taxonUsageRating' => 'taxonUsageRating',
        'unacceptReason' => 'unacceptReason',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcCoreMetadata

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcCoreMetadata from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * credRating


=item * rankId


=item * taxonCoverage


=item * taxonCurrency


=item * taxonUsageRating


=item * unacceptReason




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcCoreMetadata
   credRating =>  $some_value, # string
   rankId =>  $some_value, # int
   taxonCoverage =>  $some_value, # string
   taxonCurrency =>  $some_value, # string
   taxonUsageRating =>  $some_value, # string
   unacceptReason =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

