package MyTypes::SvcReferenceForElement;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %refLanguage_of :ATTR(:get<refLanguage>);
my %referredTsn_of :ATTR(:get<referredTsn>);

__PACKAGE__->_factory(
    [ qw(        name
        refLanguage
        referredTsn

    ) ],
    {
        'name' => \%name_of,
        'refLanguage' => \%refLanguage_of,
        'referredTsn' => \%referredTsn_of,
    },
    {
        'name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'refLanguage' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'referredTsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'name' => 'name',
        'refLanguage' => 'refLanguage',
        'referredTsn' => 'referredTsn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcReferenceForElement

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcReferenceForElement from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * refLanguage


=item * referredTsn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcReferenceForElement
   name =>  $some_value, # string
   refLanguage =>  $some_value, # string
   referredTsn =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

