package MyTypes::SvcTaxonExpertList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %experts_of :ATTR(:get<experts>);

__PACKAGE__->_factory(
    [ qw(        tsn
        experts

    ) ],
    {
        'tsn' => \%tsn_of,
        'experts' => \%experts_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'experts' => 'MyTypes::SvcTaxonExpert',
    },
    {

        'tsn' => 'tsn',
        'experts' => 'experts',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcTaxonExpertList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcTaxonExpertList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * experts




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcTaxonExpertList
   experts =>  { # MyTypes::SvcTaxonExpert
     comment =>  $some_value, # string
     expert =>  $some_value, # string
     referenceFor =>  { # MyTypes::SvcReferenceForElement
       name =>  $some_value, # string
       refLanguage =>  $some_value, # string
       referredTsn =>  $some_value, # string
     },
     updateDate =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

