# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Taxosaurus"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'
daemon: true

# port. If empty defaults to 3000. Sudo privileges are usually required to run on port 80
port: 80 

# prefix. Sets the top level resource
#prefix: "/tnrs"

#Host name
#NOTE: This does not affect the actual host, but only the links that will be shown to the user
hostname: "http://www.taxosaurus.org" 

