requires 'Dancer', '1.3111'; # 1.0 or newer
requires 'JSON', '2.53';
requires 'Carp', '1.26';
requires 'LWP::UserAgent', '6.05';
requires 'XML::Entities', '1.0002';
requires 'Parallel::ForkManager', '1.03';
requires 'utf8', '1.09';
requires 'Exporter', '5.66';
requires 'Data::Dumper', '2.145';
requires 'Digest::MD5','2.51';
requires 'Sys::Hostname', '1.16';
requires 'FindBin', '1.51';

on 'test' => sub {
  requires 'Test::More', '1.25_02';
};
 