package MyTypes::SvcCommonNameList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %commonNames_of :ATTR(:get<commonNames>);

__PACKAGE__->_factory(
    [ qw(        tsn
        commonNames

    ) ],
    {
        'tsn' => \%tsn_of,
        'commonNames' => \%commonNames_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'commonNames' => 'MyTypes::SvcCommonName',
    },
    {

        'tsn' => 'tsn',
        'commonNames' => 'commonNames',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcCommonNameList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcCommonNameList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * commonNames




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcCommonNameList
   commonNames =>  { # MyTypes::SvcCommonName
     commonName =>  $some_value, # string
     language =>  $some_value, # string
     tsn =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

