package MyTypes::SvcHierarchyRecordList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %hierarchyList_of :ATTR(:get<hierarchyList>);

__PACKAGE__->_factory(
    [ qw(        tsn
        hierarchyList

    ) ],
    {
        'tsn' => \%tsn_of,
        'hierarchyList' => \%hierarchyList_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'hierarchyList' => 'MyTypes::SvcHierarchyRecord',
    },
    {

        'tsn' => 'tsn',
        'hierarchyList' => 'hierarchyList',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcHierarchyRecordList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcHierarchyRecordList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * hierarchyList




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcHierarchyRecordList
   hierarchyList =>  { # MyTypes::SvcHierarchyRecord
     parentName =>  $some_value, # string
     parentTsn =>  $some_value, # string
     rankName =>  $some_value, # string
     taxonName =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

