package MyTypes::SvcKingdomName;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://metadata.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %kingdomId_of :ATTR(:get<kingdomId>);
my %kingdomName_of :ATTR(:get<kingdomName>);
my %tsn_of :ATTR(:get<tsn>);

__PACKAGE__->_factory(
    [ qw(        kingdomId
        kingdomName
        tsn

    ) ],
    {
        'kingdomId' => \%kingdomId_of,
        'kingdomName' => \%kingdomName_of,
        'tsn' => \%tsn_of,
    },
    {
        'kingdomId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'kingdomName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'kingdomId' => 'kingdomId',
        'kingdomName' => 'kingdomName',
        'tsn' => 'tsn',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcKingdomName

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcKingdomName from the namespace http://metadata.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * kingdomId


=item * kingdomName


=item * tsn




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcKingdomName
   kingdomId =>  $some_value, # string
   kingdomName =>  $some_value, # string
   tsn =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

