package MyTypes::SvcTaxonGeoDivisionList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %geoDivisions_of :ATTR(:get<geoDivisions>);

__PACKAGE__->_factory(
    [ qw(        tsn
        geoDivisions

    ) ],
    {
        'tsn' => \%tsn_of,
        'geoDivisions' => \%geoDivisions_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'geoDivisions' => 'MyTypes::SvcTaxonGeoDivision',
    },
    {

        'tsn' => 'tsn',
        'geoDivisions' => 'geoDivisions',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcTaxonGeoDivisionList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcTaxonGeoDivisionList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * geoDivisions




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcTaxonGeoDivisionList
   geoDivisions =>  { # MyTypes::SvcTaxonGeoDivision
     geographicValue =>  $some_value, # string
     updateDate =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

