package MyTypes::SvcTaxonComment;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %commentDetail_of :ATTR(:get<commentDetail>);
my %commentId_of :ATTR(:get<commentId>);
my %commentTimeStamp_of :ATTR(:get<commentTimeStamp>);
my %commentator_of :ATTR(:get<commentator>);
my %updateDate_of :ATTR(:get<updateDate>);

__PACKAGE__->_factory(
    [ qw(        commentDetail
        commentId
        commentTimeStamp
        commentator
        updateDate

    ) ],
    {
        'commentDetail' => \%commentDetail_of,
        'commentId' => \%commentId_of,
        'commentTimeStamp' => \%commentTimeStamp_of,
        'commentator' => \%commentator_of,
        'updateDate' => \%updateDate_of,
    },
    {
        'commentDetail' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'commentId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'commentTimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'commentator' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'updateDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'commentDetail' => 'commentDetail',
        'commentId' => 'commentId',
        'commentTimeStamp' => 'commentTimeStamp',
        'commentator' => 'commentator',
        'updateDate' => 'updateDate',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcTaxonComment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcTaxonComment from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * commentDetail


=item * commentId


=item * commentTimeStamp


=item * commentator


=item * updateDate




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcTaxonComment
   commentDetail =>  $some_value, # string
   commentId =>  $some_value, # string
   commentTimeStamp =>  $some_value, # string
   commentator =>  $some_value, # string
   updateDate =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

