package MyTypes::SvcTaxonJurisdictionalOriginList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(MyTypes::SvcListBase);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %tsn_of :ATTR(:get<tsn>);
my %jurisdictionalOrigins_of :ATTR(:get<jurisdictionalOrigins>);

__PACKAGE__->_factory(
    [ qw(        tsn
        jurisdictionalOrigins

    ) ],
    {
        'tsn' => \%tsn_of,
        'jurisdictionalOrigins' => \%jurisdictionalOrigins_of,
    },
    {
        'tsn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'jurisdictionalOrigins' => 'MyTypes::SvcTaxonJurisdictionalOrigin',
    },
    {

        'tsn' => 'tsn',
        'jurisdictionalOrigins' => 'jurisdictionalOrigins',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcTaxonJurisdictionalOriginList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcTaxonJurisdictionalOriginList from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * jurisdictionalOrigins




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcTaxonJurisdictionalOriginList
   jurisdictionalOrigins =>  { # MyTypes::SvcTaxonJurisdictionalOrigin
     jurisdictionValue =>  $some_value, # string
     origin =>  $some_value, # string
     updateDate =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

