package MyTypes::SvcTaxonPublication;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://data.itis_service.itis.usgs.org/xsd' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %actualPubDate_of :ATTR(:get<actualPubDate>);
my %isbn_of :ATTR(:get<isbn>);
my %issn_of :ATTR(:get<issn>);
my %listedPubDate_of :ATTR(:get<listedPubDate>);
my %pages_of :ATTR(:get<pages>);
my %pubComment_of :ATTR(:get<pubComment>);
my %pubName_of :ATTR(:get<pubName>);
my %pubPlace_of :ATTR(:get<pubPlace>);
my %publisher_of :ATTR(:get<publisher>);
my %referenceAuthor_of :ATTR(:get<referenceAuthor>);
my %referenceFor_of :ATTR(:get<referenceFor>);
my %title_of :ATTR(:get<title>);
my %updateDate_of :ATTR(:get<updateDate>);

__PACKAGE__->_factory(
    [ qw(        actualPubDate
        isbn
        issn
        listedPubDate
        pages
        pubComment
        pubName
        pubPlace
        publisher
        referenceAuthor
        referenceFor
        title
        updateDate

    ) ],
    {
        'actualPubDate' => \%actualPubDate_of,
        'isbn' => \%isbn_of,
        'issn' => \%issn_of,
        'listedPubDate' => \%listedPubDate_of,
        'pages' => \%pages_of,
        'pubComment' => \%pubComment_of,
        'pubName' => \%pubName_of,
        'pubPlace' => \%pubPlace_of,
        'publisher' => \%publisher_of,
        'referenceAuthor' => \%referenceAuthor_of,
        'referenceFor' => \%referenceFor_of,
        'title' => \%title_of,
        'updateDate' => \%updateDate_of,
    },
    {
        'actualPubDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'isbn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'issn' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'listedPubDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pages' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pubComment' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pubName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pubPlace' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'publisher' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'referenceAuthor' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'referenceFor' => 'MyTypes::SvcReferenceForElement',
        'title' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'updateDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'actualPubDate' => 'actualPubDate',
        'isbn' => 'isbn',
        'issn' => 'issn',
        'listedPubDate' => 'listedPubDate',
        'pages' => 'pages',
        'pubComment' => 'pubComment',
        'pubName' => 'pubName',
        'pubPlace' => 'pubPlace',
        'publisher' => 'publisher',
        'referenceAuthor' => 'referenceAuthor',
        'referenceFor' => 'referenceFor',
        'title' => 'title',
        'updateDate' => 'updateDate',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::SvcTaxonPublication

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
SvcTaxonPublication from the namespace http://data.itis_service.itis.usgs.org/xsd.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * actualPubDate


=item * isbn


=item * issn


=item * listedPubDate


=item * pages


=item * pubComment


=item * pubName


=item * pubPlace


=item * publisher


=item * referenceAuthor


=item * referenceFor


=item * title


=item * updateDate




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::SvcTaxonPublication
   actualPubDate =>  $some_value, # string
   isbn =>  $some_value, # string
   issn =>  $some_value, # string
   listedPubDate =>  $some_value, # string
   pages =>  $some_value, # string
   pubComment =>  $some_value, # string
   pubName =>  $some_value, # string
   pubPlace =>  $some_value, # string
   publisher =>  $some_value, # string
   referenceAuthor =>  $some_value, # string
   referenceFor =>  { # MyTypes::SvcReferenceForElement
     name =>  $some_value, # string
     refLanguage =>  $some_value, # string
     referredTsn =>  $some_value, # string
   },
   title =>  $some_value, # string
   updateDate =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

